blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('userlogin/',views.userlogin,name='userlogin'),
    path('singup/',views.singup,name='singup'),
    path('userLogout',views.userLogout,name='userLogout'),
    path('addpost/',views.addPost,name='addpost'),
    path('update/<int:id>/',views.updatePost,name='updatepost'),# given dynamic url to delet and update
    path('delete/<int:id>',views.deletePost,name='deletepost')

]

blog/app/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=150)
    Desc=models.TextField()

blog/app/forms.py
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm,UsernameField #  we have to modified form
from django import forms
from django.contrib.auth.models import User # we have used this inbuild model 
from django.utils.translation import ugettext_lazy as _
from . models import Post


# singup form 
class SingUpForm(UserCreationForm):
    password1=forms.CharField(label='password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        label={'first_name':'First Name','last_name':'Last Name','email':'Email'}
        widgets={'username':forms.TextInput(attrs={'class':'form-control'}),
        'first_name':forms.TextInput(attrs={'class':'form-control'}),
        'last_name':forms.TextInput(attrs={'class':'form-control'}),
        'email':forms.EmailInput(attrs={'class':'form-control'}),
        }

# login form
class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))    
    password = forms.CharField(label=_("password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'})) 

# form for update

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=['title','Desc']
        labels={'title':'Title','Desc':'Description'}
        widgets={'title':forms.TextInput(attrs={'class':'form-control'}),
        'Desc':forms.Textarea(attrs={'class':'form-control'}), }

blog/app/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from  . forms import SingUpForm,LoginForm,PostForm
from django.contrib import messages # for messgaes
from django.contrib.auth import authenticate,login,logout
from . models import Post
from django.contrib.auth.models import Group # import group for permission

# Create your views here.

# HOME
def home(request):
    post=Post.objects.all()
    return render(request,'blog/home.html',{'post':post})


# ABOUT
def about(request):
    return render(request,'blog/about.html')    



# Contact
def contact(request):
    return render(request,'blog/contact.html')        


# Dashboard
def dashboard(request):
    if request.user.is_authenticated:
        posts=Post.objects.all()
        user=request.user
        full_name=user.get_full_name()# method which will give full name with space  
        gps=user.groups.all()

        return render(request,'blog/dashboard.html',{'posts':posts,'full_name':full_name,'groups':gps})           
    else:
        return HttpResponseRedirect('/userlogin/')


# Login
def userlogin(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            form=LoginForm(request=request,data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upass=form.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,"welcome ")
                    return HttpResponseRedirect('/dashboard/')
              
          
                       
        else:
            form=LoginForm()
            return render(request,'blog/login.html',{'form':form}) 
    else:
        return HttpResponseRedirect('/dashboard/')



# singup
def singup(request):
    if request.method== "POST":
        form=SingUpForm(request.POST)
        if form.is_valid():
            messages.success(request,'Succesfully Register !')
            user=form.save() # aasingin into gropup
            group=Group.objects.get(name="Author")
            user.groups.add(group)
    else:
        form=SingUpForm()
    return render(request,'blog/singup.html',{'form':form})  


# logout
def userLogout(request):
    logout(request)
    return HttpResponseRedirect("/")



# add post 
def addPost(request):
     if request.user.is_authenticated:
        if request.method == 'POST':
            form=PostForm(request.POST)
            if form.is_valid():
                title=form.cleaned_data['title']
                Desc=form.cleaned_data['Desc']
                pst=Post(title=title,Desc=Desc)
                pst.save()
                form=PostForm()
        else:
            form=PostForm()        

        return render(request,'blog/addPost.html',{'form':form})
     else:
        return HttpResponseRedirect("/userlogin/")    
      

# update post 
def updatePost(request,id):
    if request.user.is_authenticated:
        if request.method=='POST':
            pi=Post.objects.get(pk=id)
            form=PostForm(request.POST,instance=pi)
            if form.is_valid():
                form.save()
        else:
            pi=Post.objects.get(pk=id)
            form=PostForm(instance=pi)        
        return render(request,'blog/updatePost.html',{'form':form})
    else:
        return HttpResponseRedirect('/userlogin/')            

# delete  post 
def deletePost(request,id):
    if request.user.is_authenticated:
        if request.method=='POST':
            pi=Post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect("/dashboard/")
    else:
        return HttpResponseRedirect('/userlogin/')                    

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> About Page</h3>
<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ratione porro autem sed, tempore nesciunt voluptatibus beatae laborum ea in a sapiente magni earum, nobis eaque eligendi nostrum veritatis. Quibusdam cumque harum velit fugiat officiis esse labore vel a dolore! Expedita sint deserunt totam quod iusto qui eum dignissimos excepturi commodi!</p>


<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ratione porro autem sed, tempore nesciunt voluptatibus beatae laborum ea in a sapiente magni earum, nobis eaque eligendi nostrum veritatis. Quibusdam cumque harum velit fugiat officiis esse labore vel a dolore! Expedita sint deserunt totam quod iusto qui eum dignissimos excepturi commodi!</p>

</div>
 
 

{% endblock content %} 

blog/templates/blog/addPost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> Dashbord / Add post </h3>
<form action="" method="post" novalidate>
{% csrf_token %}
{{form.as_p}}
<input value="Add" type="submit" class="btn btn-success">
<a href={% url 'dashboard' %}  class="btn btn-danger"> Cancel<a/>

</form>


</div>
  


{% endblock content %} 

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <!-- Custom -->
  <link rel="stylesheet" href="{% static 'css/style1.css' %}">

    <title>Document</title>
</head>

<body>
<div class="container-fluid">

{% include "blog/navbar.html" %}

</div>

<div class="container">

<div class="row">

<div class="col-sm-12">

{% block msg %}
    
{% endblock msg %}

</div>
</div>

<div class="row">

{% block side %}
 {% endblock side %}

 {% block content  %}
{% endblock content %}
</div>

</div>



    
    <script src= "{% static 'js/jquery1.js' %} "><script>
    <script src= "{% static 'js/popper.min.js'%} "><script>
    <script src= "{% static 'js/bootstrap.js'%} "><script>
    

</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> Contact Page</h3>
   <!-- FORM -->
 <form class="form-color">
 <div class="form-group ">
    <label for="exampleInputEmail1">Name</label>
    <input type="text" class="form-control col-md-6" id="inputname" aria-describedby="emailHelp" placeholder="Enter Name">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="Email" class="form-control col-md-6" id="email" aria-describedby="emailHelp" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Address</label>
    <input type="text" class="form-control col-md-6" id="address" aria-describedby="emailHelp" placeholder="Enter Address">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Message</label>
    <textarea type="text" class="form-control " id="message" aria-describedby="emailHelp" placeholder="Enter Message" rows="3"></textarea>
  </div>
 
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
 
 

{% endblock content %} 

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}
{% block msg %}
{% if messages %}
{% for message in messages %}
{% endfor %}
<div {% if message.tags %}  class="alert alert-{{message.tags}} aler-dismissible fade show" {% endif %}>

<strong>{{message}}</strong>
<button type="button" class="close" data-dismiss='alert' aria-label="close"> <span aria-hidden="true"> &times;</span></button>
</div>
{% endif %}
{% endblock msg %}

{% block side %}
 <div class="col-sm-2 text-white my-5 text-center">  
 <h4 class="my-5"> Profile </h4>
<h5>{{ full_name }}</h5>
{% for group in groups %}
<p> {{group.name }}</p>
{% endfor %}

</div>
{% endblock %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> Dashboard</h3>
<h4 class" text-center alert alert-info mt=3 "> Show post</h4>
<a href="{% url 'addpost' %}" class="btn btn-success my-2" >Add Post</a>

<!-- table -->
{% if posts %}
    <table class="table table-hover bg-primary">
    <thead class="thead-dark">
        <tr class="text-center">
        <th scope="col" style="width:2%">ID</th>
        <th scope="col"style="width:28%" >Tittle</th>
        <th scope="col" style="width:55%" >Description</th>
        <th scope="col" style="width:15%" >Action</th>
        </tr>
    </thead>
    <tbody>
    {% for post in posts%}
        <tr>
        <th scope="row"{{post.id}</th>
        <td>{{post.title}}</td>
        <td>{{post.Desc}}</td>
        <td class ="text-center"> 
        <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a> 
        {% if perms.app.delete_post %}
        <form  method="post" class="d-inline" action=" {% url 'deletepost' post.id %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
        </form>
        {% endif %}
        </td>
        </tr>
    {% endfor %}    
    </tbody>
    </table>
   {% else %} 
   <h5> No Record Founds</h5>
   {% endif %}  

</div>
 
 

{% endblock content %} 

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> Home Page</h3>
</div>

{% for posts in post %}
<div class="jumbotron jumbotron-fluid  jumbo-color">
  <div class="container">
    <h1 class="display-4">{{ posts.title}}</h1>
    <p class="lead">{{posts.Desc}}</p>
  </div>
</div>
  
{% endfor %}

{% endblock content %} 

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> Login page</h3>
<form action="" method="post" novalidate>
{% csrf_token %}
{% for fm in form %}
<div class="form-group">

{{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}
</small>
</div>
{% endfor %}
<input type="submit" value="Login" class="btn btn-primary">
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}    
<p class="alert alert-danger my-3"> {{error}}</p>
{% endfor %}
{% endif %}

</form>

</div>
 
 

{% endblock content %} 

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Ashish Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'contact' %}">Contact</a>
      </li>
      {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'dashboard' %}">Dashbord</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'userLogout' %}">Logout</a>
          </li>
        {% else %}  
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'singup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'userlogin' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>

blog/templates/blog/singup.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> Become An Author</h3>
{% if messages %}
{% for message in messages %}
<p {% if message.tags %} class='alert alert-{{message.tags}} mb-5 ' {% endif %} >{{message}}</p>
{% endfor %}
{% endif %}
<form action="" method="post" novalidate>
{% csrf_token %}
{% for fm in form %}
<div class="form-group">

{{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}
</small>
</div>
{% endfor %}
<input type="submit" value="submit" class="btn btn-primary">
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="alert alert-danger my-3"> {{error}}</p>
{% endfor %}
{% endif %}

</form>

</div>
 
 

{% endblock content %} 

blog/templates/blog/updatePost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5"> Dashbord /Update </h3>
<form action="" method="post" novalidate>
{% csrf_token %}
{{form.as_p}}
<input value="Update" type="submit" class="btn btn-success">
<a href={% url 'dashboard' %}  class="btn btn-danger"> Cancel<a/>

</form>


</div>
  


{% endblock content %} 